name: Binary Release

on:
  push:
    branches:
      - "master"
    paths:
      - ".version"

jobs:
  publish_binary_release:
    name: Publish binary release
    runs-on: macos-15
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.3"
      - uses: passepartoutvpn/action-release-binary-package@master
        with:
          script: "ci-generate.sh"
          framework: "openssl.xcframework"
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
